version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=simple_blog_api
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /usr/app/node_modules
      - ./:/usr/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_PORT='5432'
      - POSTGRES_DB=simple_blog_api
      - POSTGRES_USERNAME=postgres
    ports:
      - "3000:3000"