apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: maha6190/simple-web
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: PGHOST
              value: postgres-ip-cluster-service
            - name: PGPORT
              value: '5432'
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: POSTGRES_PASSWORD
